export type SQLQuestion = {
  id: number;
  category: string;
  question: string;
  query: string;
  columns: string[];
  result: Record<string, string | number>[];
};

const sqlQuestions: SQLQuestion[] = [
  {
    id: 1,
    category: "Revenue",
    question: "What is the total revenue generated by male vs. female customers?",
    query: `SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;`,
    columns: ["gender", "revenue"],
    result: [
      { gender: "Female", revenue: "$75,191" },
      { gender: "Male",   revenue: "$1,57,890" },
    ],
  },
  {
    id: 2,
    category: "Customers",
    question: "Which customers used a discount but still spent more than the average purchase amount?",
    query: `SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
    SELECT AVG(purchase_amount) FROM customer
  );`,
    columns: ["customer_id", "purchase_amount"],
    result: [
      { customer_id: 2,  purchase_amount: 64  },
      { customer_id: 3,  purchase_amount: 73  },
      { customer_id: 4,  purchase_amount: 90  },
      { customer_id: 7,  purchase_amount: 85  },
      { customer_id: 9,  purchase_amount: 97  },
      { customer_id: 12, purchase_amount: 68  },
      { customer_id: 13, purchase_amount: 72  },
      { customer_id: 16, purchase_amount: 81  },
      { customer_id: 20, purchase_amount: 90  },
      { customer_id: 22, purchase_amount: 62  },
    ],
    // note: showing first 10 rows — full result has 500+ rows
  },
  {
    id: 3,
    category: "Products",
    question: "Which are the top 5 products with the highest average review rating?",
    query: `SELECT item_purchased,
  ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;`,
    columns: ["item_purchased", "Average Product Rating"],
    result: [
      { item_purchased: "Gloves",  "Average Product Rating": 3.86 },
      { item_purchased: "Sandals", "Average Product Rating": 3.84 },
      { item_purchased: "Boots",   "Average Product Rating": 3.82 },
      { item_purchased: "Hat",     "Average Product Rating": 3.80 },
      { item_purchased: "Skirt",   "Average Product Rating": 3.78 },
    ],
  },
  {
    id: 4,
    category: "Shipping",
    question: "Compare the average purchase amounts between Standard and Express shipping.",
    query: `SELECT shipping_type,
  ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;`,
    columns: ["shipping_type", "avg_purchase"],
    result: [
      { shipping_type: "Standard", avg_purchase: 58.46 },
      { shipping_type: "Express",  avg_purchase: 60.48 },
    ],
  },
  {
    id: 5,
    category: "Subscribers",
    question: "Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.",
    query: `SELECT subscription_status,
  COUNT(customer_id)          AS total_customers,
  ROUND(AVG(purchase_amount), 2) AS avg_spend,
  ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;`,
    columns: ["subscription_status", "total_customers", "avg_spend", "total_revenue"],
    result: [
      { subscription_status: "Yes", total_customers: 1053, avg_spend: 59.49, total_revenue: "$62,645" },
      { subscription_status: "No",  total_customers: 2847, avg_spend: 59.87, total_revenue: "$1,70,436" },
    ],
  },
  {
    id: 6,
    category: "Discounts",
    question: "Which 5 products have the highest percentage of purchases with discounts applied?",
    query: `SELECT item_purchased,
  ROUND(
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
    2
  ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;`,
    columns: ["item_purchased", "discount_rate"],
    result: [
      { item_purchased: "Hat",      discount_rate: "50.00%" },
      { item_purchased: "Sneakers", discount_rate: "49.66%" },
      { item_purchased: "Coat",     discount_rate: "49.07%" },
      { item_purchased: "Sweater",  discount_rate: "48.17%" },
      { item_purchased: "Pants",    discount_rate: "47.37%" },
    ],
  },
  {
    id: 7,
    category: "Customers",
    question: "Segment customers into New, Returning, and Loyal based on their total number of previous purchases.",
    query: `WITH customer_type AS (
  SELECT customer_id, previous_purchases,
    CASE
      WHEN previous_purchases = 1            THEN 'New'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM customer
)
SELECT customer_segment,
  COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;`,
    columns: ["customer_segment", "Number of Customers"],
    result: [
      { customer_segment: "Loyal",     "Number of Customers": 3116 },
      { customer_segment: "Returning", "Number of Customers": 701  },
      { customer_segment: "New",       "Number of Customers": 83   },
    ],
  },
  {
    id: 8,
    category: "Products",
    question: "What are the top 3 most purchased products within each category?",
    query: `WITH item_counts AS (
  SELECT category, item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER (
      PARTITION BY category ORDER BY COUNT(customer_id) DESC
    ) AS item_rank
  FROM customer
  GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;`,
    columns: ["item_rank", "category", "item_purchased", "total_orders"],
    result: [
      { item_rank: 1, category: "Accessories", item_purchased: "Jewelry",    total_orders: 171 },
      { item_rank: 2, category: "Accessories", item_purchased: "Sunglasses", total_orders: 161 },
      { item_rank: 3, category: "Accessories", item_purchased: "Belt",       total_orders: 161 },
      { item_rank: 1, category: "Clothing",    item_purchased: "Blouse",     total_orders: 171 },
      { item_rank: 2, category: "Clothing",    item_purchased: "Pants",      total_orders: 171 },
      { item_rank: 3, category: "Clothing",    item_purchased: "Shirt",      total_orders: 169 },
      { item_rank: 1, category: "Footwear",    item_purchased: "Sandals",    total_orders: 160 },
      { item_rank: 2, category: "Footwear",    item_purchased: "Shoes",      total_orders: 150 },
      { item_rank: 3, category: "Footwear",    item_purchased: "Sneakers",   total_orders: 145 },
      { item_rank: 1, category: "Outerwear",   item_purchased: "Jacket",     total_orders: 163 },
      { item_rank: 2, category: "Outerwear",   item_purchased: "Coat",       total_orders: 161 },
    ],
  },
  {
    id: 9,
    category: "Subscribers",
    question: "Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?",
    query: `SELECT subscription_status,
  COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;`,
    columns: ["subscription_status", "repeat_buyers"],
    result: [
      { subscription_status: "No",  repeat_buyers: 2518 },
      { subscription_status: "Yes", repeat_buyers: 958  },
    ],
  },
  {
    id: 10,
    category: "Revenue",
    question: "What is the revenue contribution of each age group?",
    query: `SELECT age_group,
  SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;`,
    columns: ["age_group", "total_revenue"],
    result: [
      { age_group: "Young-adult",  total_revenue: "$62,143" },
      { age_group: "Middle-aged",  total_revenue: "$59,197" },
      { age_group: "Adult",        total_revenue: "$55,978" },
      { age_group: "Senior",       total_revenue: "$55,763" },
    ],
  },
];

export default sqlQuestions;